import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const here=dirname(fileURLToPath(import.meta.url));
const publicDir=resolve(here,'../public');
const artifactDir=resolve(here,'../../../artifacts/chrome-extension-unpacked');
async function text(root:string,name:string){return readFile(resolve(root,name),'utf8');}

function stableManifest(value:any){return{manifest_version:value.manifest_version,description:value.description,minimum_chrome_version:value.minimum_chrome_version,host_permissions:value.host_permissions,background:value.background,action:{default_popup:value.action?.default_popup},content_scripts:value.content_scripts};}
function pngInfo(buffer:Buffer){assert.equal(buffer.subarray(0,8).toString('hex'),'89504e470d0a1a0a','not a PNG');assert.equal(buffer.subarray(12,16).toString('ascii'),'IHDR','missing IHDR');const colorType=buffer[25];let offset=8,hasTransparencyChunk=false,hasIend=false;while(offset+12<=buffer.length){const length=buffer.readUInt32BE(offset);const type=buffer.subarray(offset+4,offset+8).toString('ascii');if(type==='tRNS')hasTransparencyChunk=true;if(type==='IEND'){hasIend=true;break;}offset+=12+length;}assert.equal(hasIend,true,'PNG must contain a complete IEND chunk');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20),colorType,hasTransparencyChunk};}
function assertTransparencyCapable(info:ReturnType<typeof pngInfo>){assert.ok(info.colorType===4||info.colorType===6||(info.colorType===3&&info.hasTransparencyChunk),'PNG must preserve transparency');}

test('validated browser capabilities stay aligned while local transcription adds offscreen and cross-origin isolation',async()=>{const current=JSON.parse(await text(publicDir,'manifest.json'));const preserved=JSON.parse(await text(artifactDir,'manifest.json'));assert.deepEqual(stableManifest(current),stableManifest(preserved));for(const permission of preserved.permissions)assert.ok(current.permissions.includes(permission));assert.deepEqual(current.permissions.filter((item:string)=>!preserved.permissions.includes(item)),['offscreen']);assert.equal(current.name,'SelfRelay');assert.equal(current.version,'0.4.3');assert.equal(current.action.default_title,'SelfRelay');assert.match(current.content_security_policy.extension_pages,/wasm-unsafe-eval/);assert.doesNotMatch(current.content_security_policy.extension_pages,/https?:/);assert.equal(current.cross_origin_embedder_policy?.value,'require-corp');assert.equal(current.cross_origin_opener_policy?.value,'same-origin');const resources=current.web_accessible_resources.flatMap((item:any)=>item.resources);assert.ok(resources.includes('icons/icon32.png'));assert.ok(!resources.includes('icons/selfrelay-logo.png'));});

test('popup is follow-first, compact and keeps advanced scopes behind a real disclosure',async()=>{const popup=await text(publicDir,'popup.html');assert.match(popup,/Seguir esta pestaña/);assert.match(popup,/Seguir varias pestañas/);assert.match(popup,/Añadir pestañas/);assert.match(popup,/Opciones de seguimiento/);assert.match(popup,/aria-expanded="false"/);assert.match(popup,/aria-controls="simplePanel"/);assert.match(popup,/id="simplePanel" class="simple-panel" hidden/);assert.match(popup,/id="tabPicker"/);assert.match(popup,/product-polish\.css/);for(const label of ['Pestaña','Página','Sitio'])assert.match(popup,new RegExp(`>${label}<`));assert.match(popup,/icons\/icon32\.png/);assert.doesNotMatch(popup,/icons\/selfrelay-logo\.png|state-badge|trackingBadge|Crear contexto|Elegir varias pestañas/);});

test('exit composer makes typed notes and voice notes explicit while preserving targeting',async()=>{const checkpoint=await text(publicDir,'checkpoint.html');for(const id of ['text','record','recording','timer','levelMeter','stopRecording','cancelRecording','audioReview','preview','redoRecording','checkpointTargets','targetClosed','targetAll','targetCustom','targetList','save'])assert.match(checkpoint,new RegExp(`id="${id}"`));assert.match(checkpoint,/¿Dónde quedaste\?/);assert.match(checkpoint,/Escribí una nota/);assert.match(checkpoint,/Grabar nota de voz/);assert.match(checkpoint,/Anotá qué estabas haciendo o cuál es el próximo paso/);assert.match(checkpoint,/Nota de voz/);assert.match(checkpoint,/Guardar para/);assert.match(checkpoint,/product-polish\.css/);assert.doesNotMatch(checkpoint,/Transcribiendo|Transcripción|transcript|Procesado en este dispositivo|CHECKPOINT DE SALIDA/i);const source=await text(resolve(publicDir,'../src'),'checkpoint.ts');assert.doesNotMatch(source,/transcribeLocally|TRANSCRIBE_CHECKPOINT/);assert.match(source,/transcript:null,transcriptionEngine:null/);assert.match(source,/Cerraste \$\{closedCount\} pestañas/);assert.match(source,/hasOwnProperty\.call\(result\.pending,'defaultTargetMemberIds'\)/);assert.match(source,/await stopActiveRecording\('save'\)/);assert.match(source,/await assetStore\.put/);});

test('recovery uses packaged icon and exposes transcription only behind an explicit user action',async()=>{const source=await text(resolve(publicDir,'../src'),'content.ts');assert.match(source,/icons\/icon32\.png/);assert.match(source,/class=\"brand-logo\"/);assert.match(source,/Transcribir audio/);assert.match(source,/TRANSCRIBE_CHECKPOINT/);assert.match(source,/transcribe\.onclick=/);assert.match(source,/Lo veo después/);assert.match(source,/unresolvedRecoveryStack/);assert.doesNotMatch(source,/AI is transcribing|inteligencia artificial/i);});

test('visual system uses a compact utility header, robust hidden states and reduced motion',async()=>{const css=(await text(publicDir,'ui.css'))+'\n'+(await text(publicDir,'product-polish.css'));assert.match(css,/IBM Plex Sans/);assert.match(css,/fonts\/IBMPlexSans-Regular\.woff2/);assert.match(css,/#0d1b2a/i);assert.match(css,/#2168f3/i);assert.match(css,/\[hidden\]\{display:none!important\}/);assert.match(css,/disclosure\[aria-expanded="true"\]/);assert.match(css,/prefers-reduced-motion/);assert.match(css,/voice-action/);assert.doesNotMatch(css,/#315f4c|#f5f5f2|#fffdf8|linear-gradient|glassmorphism|backdrop-filter/i);});

test('all visible SelfRelay-owned surfaces use the same known-good UI icon beside the brand',async()=>{for(const page of ['popup.html','checkpoint.html','audio.html']){const html=await text(publicDir,page);assert.match(html,/class="identity"[^>]*>\s*<img class="logo" src="icons\/icon32\.png" alt="">\s*<span>SelfRelay<\/span>/);}const recovery=await text(resolve(publicDir,'../src'),'content.ts');assert.match(recovery,/brand-logo[^>]*src=\"\$\{logoUrl\}\"[^>]*alt=\"\">SelfRelay/);});

test('official SelfRelay icon set is declared with complete PNGs, correct dimensions and transparency',async()=>{const manifest=JSON.parse(await text(publicDir,'manifest.json'));for(const size of [16,32,48,128]){const relative=`icons/icon${size}.png`;assert.equal(manifest.icons[String(size)],relative);assert.equal(manifest.action.default_icon[String(size)],relative);const info=pngInfo(await readFile(resolve(publicDir,relative)));assert.deepEqual([info.width,info.height],[size,size]);assertTransparencyCapable(info);}});

test('transcription diagnostic path no longer swallows packaged runtime failures',async()=>{const source=await text(resolve(publicDir,'../src'),'transcription.ts'),worker=await text(resolve(publicDir,'vendor/whisper'),'selfrelay-whisper-worker.js'),offscreen=await text(resolve(publicDir,'../src'),'offscreen.ts');assert.match(source,/LocalTranscriptionError/);assert.doesNotMatch(source,/catch\{return null;\}/);for(const code of ['worker_load_failed','audio_decode_failed','timeout'])assert.match(source,new RegExp(code));for(const code of ['cross_origin_isolation_missing','wasm_load_failed','model_fetch_failed','model_init_failed','whisper_runtime_failed'])assert.match(worker,new RegExp(code));assert.match(offscreen,/console\.error\('\[SelfRelay transcription\]'/);});
