import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {inflateSync} from 'node:zlib';
import test from 'node:test';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const here=dirname(fileURLToPath(import.meta.url));
const publicDir=resolve(here,'../public');
const artifactDir=resolve(here,'../../../artifacts/chrome-extension-unpacked');
async function text(root:string,name:string){return readFile(resolve(root,name),'utf8');}

function stableManifest(value:any){return{manifest_version:value.manifest_version,description:value.description,minimum_chrome_version:value.minimum_chrome_version,host_permissions:value.host_permissions,background:value.background,action:{default_popup:value.action?.default_popup},content_scripts:value.content_scripts};}
function pngInfo(buffer:Buffer){assert.equal(buffer.subarray(0,8).toString('hex'),'89504e470d0a1a0a','not a PNG');assert.equal(buffer.subarray(12,16).toString('ascii'),'IHDR','missing IHDR');const colorType=buffer[25];let offset=8,hasTransparencyChunk=false;while(offset+12<=buffer.length){const length=buffer.readUInt32BE(offset),type=buffer.subarray(offset+4,offset+8).toString('ascii');if(type==='tRNS')hasTransparencyChunk=true;offset+=12+length;if(type==='IEND')break;}return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20),bitDepth:buffer[24],colorType,hasTransparencyChunk};}
function assertTransparencyCapable(info:ReturnType<typeof pngInfo>){assert.ok(info.colorType===4||info.colorType===6||(info.colorType===3&&info.hasTransparencyChunk),'PNG must preserve transparency');}
function paeth(a:number,b:number,c:number){const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;}
function rgbaVisibleBounds(buffer:Buffer){const info=pngInfo(buffer);assert.equal(info.bitDepth,8);assert.equal(info.colorType,6,'UI mark test expects RGBA PNG');let offset=8;const idat:Buffer[]=[];while(offset+12<=buffer.length){const length=buffer.readUInt32BE(offset),type=buffer.subarray(offset+4,offset+8).toString('ascii');if(type==='IDAT')idat.push(buffer.subarray(offset+8,offset+8+length));offset+=12+length;if(type==='IEND')break;}const raw=inflateSync(Buffer.concat(idat)),stride=info.width*4,reconstructed=Buffer.alloc(stride*info.height);let cursor=0;for(let y=0;y<info.height;y++){const filter=raw[cursor++]!,row=raw.subarray(cursor,cursor+stride);cursor+=stride;for(let x=0;x<stride;x++){const left=x>=4?reconstructed[y*stride+x-4]!:0,up=y?reconstructed[(y-1)*stride+x]!:0,upLeft=y&&x>=4?reconstructed[(y-1)*stride+x-4]!:0,value=row[x]!;const add=filter===0?0:filter===1?left:filter===2?up:filter===3?Math.floor((left+up)/2):filter===4?paeth(left,up,upLeft):NaN;assert.ok(Number.isFinite(add),'unsupported PNG filter');reconstructed[y*stride+x]=(value+add)&255;}}let minX=info.width,minY=info.height,maxX=-1,maxY=-1,visible=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++){const alpha=reconstructed[y*stride+x*4+3]!;if(alpha>12){visible++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}}assert.ok(visible>0,'UI mark has no visible alpha pixels');return{...info,visible,minX,minY,maxX,maxY,widthUsed:maxX-minX+1,heightUsed:maxY-minY+1};}

test('validated browser capabilities stay aligned and local Whisper opts into cross-origin isolation',async()=>{const current=JSON.parse(await text(publicDir,'manifest.json'));const preserved=JSON.parse(await text(artifactDir,'manifest.json'));assert.deepEqual(stableManifest(current),stableManifest(preserved));for(const permission of preserved.permissions)assert.ok(current.permissions.includes(permission));assert.deepEqual(current.permissions.filter((item:string)=>!preserved.permissions.includes(item)),['offscreen']);assert.equal(current.name,'SelfRelay');assert.equal(current.version,'0.4.1');assert.equal(current.action.default_title,'SelfRelay');assert.match(current.content_security_policy.extension_pages,/wasm-unsafe-eval/);assert.doesNotMatch(current.content_security_policy.extension_pages,/https?:/);assert.equal(current.cross_origin_embedder_policy?.value,'require-corp');assert.equal(current.cross_origin_opener_policy?.value,'same-origin');const resources=current.web_accessible_resources.flatMap((item:any)=>item.resources);assert.ok(resources.includes('icons/icon32.png'));assert.ok(!resources.includes('icons/selfrelay-logo.png'));});

test('popup is workset-first and advanced tracking is a closed accessible disclosure',async()=>{const popup=await text(publicDir,'popup.html'),source=await text(resolve(publicDir,'../src'),'popup.ts'),css=await text(publicDir,'ui.css');assert.match(popup,/Crear contexto/);assert.match(popup,/Elegir varias pestañas/);assert.match(popup,/Seguimiento avanzado/);assert.match(popup,/id="simpleToggle"[^>]*aria-expanded="false"[^>]*aria-controls="simplePanel"/);assert.match(popup,/id="simplePanel"[^>]*hidden/);assert.match(source,/function setSimpleDisclosure\(open:boolean\)/);assert.match(source,/setAttribute\('aria-expanded',String\(open\)\)/);assert.match(source,/simpleToggle\.onclick=.*setSimpleDisclosure/);assert.match(css,/\[hidden\]\{display:none!important\}/);assert.match(css,/\[aria-expanded="true"\] \.disclosure-chevron\{transform:rotate\(180deg\)\}/);for(const label of ['Pestaña','Página','Sitio'])assert.match(popup,new RegExp(`>${label}<`));assert.doesNotMatch(popup,/Seguimiento por página o sitio/);});

test('exit composer records audio and exposes closed, whole-context and custom targeting',async()=>{const checkpoint=await text(publicDir,'checkpoint.html');for(const id of ['text','record','recording','timer','levelMeter','stopRecording','cancelRecording','audioReview','preview','redoRecording','checkpointTargets','targetClosed','targetAll','targetCustom','targetList','save'])assert.match(checkpoint,new RegExp(`id="${id}"`));assert.match(checkpoint,/¿Dónde quedaste\?/);assert.match(checkpoint,/Guardar para/);assert.doesNotMatch(checkpoint,/Transcribiendo|Transcripción|transcript|Procesado en este dispositivo|CHECKPOINT DE SALIDA/i);const source=await text(resolve(publicDir,'../src'),'checkpoint.ts');assert.doesNotMatch(source,/transcribeLocally|TRANSCRIBE_CHECKPOINT/);assert.match(source,/transcript:null,transcriptionEngine:null/);assert.match(source,/Cerraste \$\{closedCount\} pestañas/);assert.match(source,/hasOwnProperty\.call\(result\.pending,'defaultTargetMemberIds'\)/);});

test('recovery exposes transcription only behind explicit user action and preserves diagnostics',async()=>{const source=await text(resolve(publicDir,'../src'),'content.ts');assert.match(source,/icons\/icon32\.png/);assert.match(source,/Transcribir audio/);assert.match(source,/TRANSCRIBE_CHECKPOINT/);assert.match(source,/transcribe\.onclick=/);assert.match(source,/SelfRelay transcription/);assert.doesNotMatch(source,/AI is transcribing|inteligencia artificial/i);});

test('visual system uses compact utility hierarchy, local IBM Plex and reduced-motion support',async()=>{const css=await text(publicDir,'ui.css');assert.match(css,/IBM Plex Sans/);assert.match(css,/fonts\/IBMPlexSans-Regular\.woff2/);assert.match(css,/#0d1b2a/i);assert.match(css,/#2168f3/i);assert.match(css,/prefers-reduced-motion/);assert.match(css,/\.app-header\{height:50px/);assert.doesNotMatch(css,/#315f4c|#f5f5f2|#fffdf8|linear-gradient|glassmorphism|backdrop-filter/i);});

test('all visible SelfRelay-owned surfaces use the valid 32px mark beside the brand',async()=>{for(const page of ['popup.html','checkpoint.html','audio.html']){const html=await text(publicDir,page);assert.match(html,/class="identity"[^>]*>\s*<img class="logo" src="icons\/icon32\.png" alt="">\s*<span>SelfRelay<\/span>/);}const recovery=await text(resolve(publicDir,'../src'),'content.ts');assert.match(recovery,/logoUrl=chrome\.runtime\.getURL\('icons\/icon32\.png'\)/);});

test('packaged UI mark has useful visible alpha bounds instead of an empty or corrupt canvas',async()=>{const mark=rgbaVisibleBounds(await readFile(resolve(publicDir,'icons/icon32.png')));assert.deepEqual([mark.width,mark.height],[32,32]);assert.ok(mark.visible>=80,'UI mark must contain enough visible pixels');assert.ok(mark.widthUsed/mark.width>=.55,'visible mark is too narrow for a 24px header');assert.ok(mark.heightUsed/mark.height>=.55,'visible mark is too short for a 24px header');});

test('official SelfRelay extension icon set keeps correct dimensions and transparency',async()=>{const manifest=JSON.parse(await text(publicDir,'manifest.json'));for(const size of [16,32,48,128]){const relative=`icons/icon${size}.png`;assert.equal(manifest.icons[String(size)],relative);assert.equal(manifest.action.default_icon[String(size)],relative);const info=pngInfo(await readFile(resolve(publicDir,relative)));assert.deepEqual([info.width,info.height],[size,size]);assertTransparencyCapable(info);}});
