import assert from 'node:assert/strict';
import test from 'node:test';
import {createBackgroundController} from '../src/background-core.ts';
import type {AudioAssetStore,StoredAudioAsset} from '../src/audio-store.ts';

class Event<T extends (...args:any[])=>any>{listeners:T[]=[];addListener=(listener:T)=>{this.listeners.push(listener);};}
class Area{data:Record<string,any>={};async get(key:string|string[]|Record<string,any>|null){if(typeof key==='string')return{[key]:this.data[key]};if(Array.isArray(key))return Object.fromEntries(key.map(item=>[item,this.data[item]]));if(key&&typeof key==='object')return Object.fromEntries(Object.entries(key).map(([item,fallback])=>[item,this.data[item]??fallback]));return{...this.data};}async set(value:Record<string,any>){Object.assign(this.data,value);}async setAccessLevel(){}}
function fakeChrome(){const local=new Area(),session=new Area();const tabs:any[]=[];const createdWindows:any[]=[];const api:any={storage:{local,session},tabs:{query:async(query:any)=>query?.active?tabs.filter(tab=>tab.active):tabs,onCreated:new Event(),onUpdated:new Event(),onRemoved:new Event()},windows:{create:async(options:any)=>{const created={id:100+createdWindows.length,...options};createdWindows.push(created);return created;},getAll:async()=>[{id:10,type:'normal'}],onRemoved:new Event()},runtime:{getURL:(path:string)=>`chrome-extension://selfrelay/${path}`,onInstalled:new Event(),onStartup:new Event(),onMessage:new Event()}};return{api,tabs,createdWindows};}
function memoryAudioStore(){const assets=new Map<string,StoredAudioAsset>();const deleted:string[]=[];const store:AudioAssetStore={async put(asset){assets.set(asset.id,asset);},async get(id){return assets.get(id)??null;},async delete(id){deleted.push(id);assets.delete(id);},async has(id){return assets.has(id);}};return{store,assets,deleted};}
function ids(){let value=0;return()=>`id-${++value}`;}
const now=()=> '2026-08-22T07:00:00.000Z';
async function pendingController(){const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'https://example.com/work',title:'Work',active:true});const audio=memoryAudioStore();const controller=createBackgroundController(env.api,{now,uuid:ids(),audioStore:audio.store});await controller.trackContext('url');await controller.handleRemoved(1,false,10);const pending=(await controller.storage.getPending())[0]!;return{env,audio,controller,pending};}

test('legacy text-only checkpoint remains valid',async()=>{const {controller,pending}=await pendingController();const result:any=await controller.saveCheckpoint(pending.id,'Terminar la validación.');assert.equal(result.ok,true);assert.equal(result.checkpoint.originalText,'Terminar la validación.');assert.equal(result.checkpoint.audioRef,null);assert.equal(result.checkpoint.transcript,null);});

test('audio-only checkpoint saves without forcing text',async()=>{const {controller,pending}=await pendingController();const result:any=await controller.saveCheckpoint(pending.id,{audioRef:'audio-1',audioMimeType:'audio/webm;codecs=opus',audioDurationMs:4200});assert.equal(result.ok,true);assert.equal(result.checkpoint.originalText,'');assert.equal(result.checkpoint.audioRef,'audio-1');assert.equal(result.checkpoint.audioDurationMs,4200);});

test('audio plus local transcript keeps transcript as checkpoint metadata',async()=>{const {controller,pending}=await pendingController();const result:any=await controller.saveCheckpoint(pending.id,{audioRef:'audio-2',transcript:'Mañana revisar autenticación.',transcriptionEngine:'whisper-local'});assert.equal(result.ok,true);assert.equal(result.checkpoint.transcript,'Mañana revisar autenticación.');assert.equal(result.checkpoint.transcriptionEngine,'whisper-local');});

test('typed text and audio coexist in one checkpoint',async()=>{const {controller,pending}=await pendingController();const result:any=await controller.saveCheckpoint(pending.id,{text:'Error al guardar.',audioRef:'audio-3',transcript:'Siguiente paso revisar el formulario.',transcriptionEngine:'browser-local'});assert.equal(result.ok,true);assert.equal(result.checkpoint.originalText,'Error al guardar.');assert.equal(result.checkpoint.audioRef,'audio-3');assert.equal(result.checkpoint.transcript,'Siguiente paso revisar el formulario.');});

test('transcription failure never discards a valid audio checkpoint',async()=>{const {controller,pending}=await pendingController();const result:any=await controller.saveCheckpoint(pending.id,{audioRef:'audio-4',audioMimeType:'audio/webm',transcript:null,transcriptionEngine:null});assert.equal(result.ok,true);assert.equal(result.checkpoint.audioRef,'audio-4');assert.equal(result.checkpoint.transcript,null);});

test('audio playback opens only the packaged local player',async()=>{const {controller,env}=await pendingController();const result:any=await controller.handleMessage({type:'OPEN_AUDIO_PLAYER',audioRef:'audio-5'});assert.equal(result.ok,true);assert.equal(env.createdWindows.at(-1).url,'chrome-extension://selfrelay/audio.html?ref=audio-5');});

test('resolving an audio checkpoint removes its blob reference and asset',async()=>{const {controller,pending,audio}=await pendingController();audio.assets.set('audio-6',{id:'audio-6',blob:new Blob(['audio']),mimeType:'audio/webm',durationMs:1000,createdAt:now()});const saved:any=await controller.saveCheckpoint(pending.id,{audioRef:'audio-6',transcript:'Retomar acá.',transcriptionEngine:'whisper-local'});const resolved:any=await controller.resolveCheckpoint(saved.checkpoint.id);assert.equal(resolved.ok,true);assert.deepEqual(audio.deleted,['audio-6']);const history:any=await controller.getContextHistory(saved.checkpoint.contextId);assert.equal(history.checkpoints[0].audioRef,null);assert.equal(history.checkpoints[0].transcript,'Retomar acá.');assert.equal(history.checkpoints[0].resolvedAt,now());});

test('deleting an audio checkpoint removes the blob before metadata',async()=>{const {controller,pending,audio}=await pendingController();audio.assets.set('audio-7',{id:'audio-7',blob:new Blob(['audio']),mimeType:'audio/webm',durationMs:1000,createdAt:now()});const saved:any=await controller.saveCheckpoint(pending.id,{audioRef:'audio-7'});const deleted:any=await controller.deleteCheckpoint(saved.checkpoint.id);assert.equal(deleted.ok,true);assert.deepEqual(audio.deleted,['audio-7']);const history:any=await controller.getContextHistory(saved.checkpoint.contextId);assert.equal(history.checkpoints.length,0);});

test('failed audio cleanup leaves checkpoint unresolved for a safe retry',async()=>{const {controller,pending}=await pendingController();const failing:AudioAssetStore={put:async()=>{},get:async()=>null,delete:async()=>{throw new Error('disk');},has:async()=>true};const env=fakeChrome();const retry=createBackgroundController(env.api,{now,uuid:ids(),audioStore:failing});await retry.storage.setPending([pending]);const saved:any=await retry.saveCheckpoint(pending.id,{audioRef:'audio-8'});const result:any=await retry.resolveCheckpoint(saved.checkpoint.id);assert.equal(result.ok,false);assert.equal(result.error,'audio_cleanup_failed');const stored=(await retry.storage.getCheckpoints())[0]!;assert.equal(stored.resolvedAt,null);assert.equal(stored.audioRef,'audio-8');});
