import assert from 'node:assert/strict';
import test from 'node:test';
import {createBackgroundController} from '../src/background-core.ts';
import {unresolvedRecoveryStack} from '../src/recovery-stack.ts';

class Event<T extends (...args:any[])=>any>{listeners:T[]=[];addListener=(listener:T)=>{this.listeners.push(listener);};}
class Area{data:Record<string,any>={};async get(key:string|string[]|Record<string,any>|null){if(typeof key==='string')return{[key]:this.data[key]};if(Array.isArray(key))return Object.fromEntries(key.map(item=>[item,this.data[item]]));if(key&&typeof key==='object')return Object.fromEntries(Object.entries(key).map(([item,fallback])=>[item,this.data[item]??fallback]));return{...this.data};}async set(value:Record<string,any>){Object.assign(this.data,value);}async setAccessLevel(){}}
function fakeChrome(){const local=new Area(),session=new Area();const api:any={storage:{local,session},tabs:{query:async()=>[],create:async()=>({}),onCreated:new Event(),onUpdated:new Event(),onRemoved:new Event()},windows:{create:async()=>({id:1}),getAll:async()=>[],onRemoved:new Event()},runtime:{getURL:(path:string)=>`chrome-extension://selfrelay/${path}`,sendMessage:async()=>({ok:false}),onInstalled:new Event(),onStartup:new Event(),onMessage:new Event()},offscreen:{hasDocument:async()=>true,createDocument:async()=>{}}};return{api,local,session};}

function pending(id:string){return{id,contextId:'context',url:'https://a.example/work',title:'Work',closedAt:'2026-08-22T09:00:00.000Z',memberId:'member-a',closedMembers:[{memberId:'member-a',url:'https://a.example/work',title:'Work'}],defaultTargetMemberIds:['member-a']};}

test('saving A B and C appends unresolved checkpoints and individual resolution preserves the others',async()=>{
  const env=fakeChrome();let id=0,timeIndex=0;const times=['2026-08-22T09:20:00.000Z','2026-08-22T11:45:00.000Z','2026-08-22T14:10:00.000Z','2026-08-22T15:00:00.000Z','2026-08-22T15:01:00.000Z','2026-08-22T15:02:00.000Z'];const controller=createBackgroundController(env.api,{uuid:()=>`checkpoint-${++id}`,now:()=>times[Math.min(timeIndex++,times.length-1)]!});
  await controller.storage.setContexts([{id:'context',type:'browser',contextKey:'browser:workset:context',scope:'url',url:'https://a.example/work',origin:'https://a.example',title:'Work',faviconUrl:null,trackedTabId:null,members:[{id:'member-a',url:'https://a.example/work',title:'Work',faviconUrl:null,order:0,addedAt:'2026-08-22T08:00:00.000Z'}],createdAt:'2026-08-22T08:00:00.000Z',updatedAt:'2026-08-22T08:00:00.000Z'}]);
  for(const [pendingId,text] of [['pending-a','A'],['pending-b','B'],['pending-c','C']] as const){await controller.storage.setPending([pending(pendingId)]);const saved:any=await controller.saveCheckpoint(pendingId,{text});assert.equal(saved.ok,true);}
  let all=await controller.storage.getCheckpoints();assert.equal(all.length,3);assert.equal(all.every(item=>item.resolvedAt===null),true);assert.deepEqual(unresolvedRecoveryStack([all[2]!,all[0]!,all[1]!],'member-a').map(item=>item.originalText),['A','B','C']);
  const b=all.find(item=>item.originalText==='B')!;assert.equal((await controller.resolveCheckpoint(b.id) as any).ok,true);all=await controller.storage.getCheckpoints();assert.equal(all.find(item=>item.originalText==='A')?.resolvedAt,null);assert.ok(all.find(item=>item.originalText==='B')?.resolvedAt);assert.equal(all.find(item=>item.originalText==='C')?.resolvedAt,null);assert.deepEqual(unresolvedRecoveryStack(all,'member-a').map(item=>item.originalText),['A','C']);
  const a=all.find(item=>item.originalText==='A')!,c=all.find(item=>item.originalText==='C')!;assert.equal((await controller.resolveCheckpoint(a.id) as any).ok,true);assert.deepEqual(unresolvedRecoveryStack(await controller.storage.getCheckpoints(),'member-a').map(item=>item.originalText),['C']);assert.equal((await controller.resolveCheckpoint(c.id) as any).ok,true);assert.deepEqual(unresolvedRecoveryStack(await controller.storage.getCheckpoints(),'member-a'),[]);
});
