import assert from 'node:assert/strict';
import test from 'node:test';
import type {BrowserContext} from '@selfrelay/shared';
import {createBackgroundController,findBestContext} from '../src/background-core.ts';
import {contextKey,matches,normalizeUrl} from '../src/url.ts';

class Event<T extends (...args:any[])=>any>{listeners:T[]=[];addListener=(listener:T)=>{this.listeners.push(listener);};async emit(...args:Parameters<T>){for(const listener of this.listeners)await listener(...args);}}
class Area{data:Record<string,any>={};async get(key:string|string[]|Record<string,any>|null){if(typeof key==='string')return{[key]:this.data[key]};if(Array.isArray(key))return Object.fromEntries(key.map(item=>[item,this.data[item]]));if(key&&typeof key==='object')return Object.fromEntries(Object.entries(key).map(([item,fallback])=>[item,this.data[item]??fallback]));return{...this.data};}async set(value:Record<string,any>){Object.assign(this.data,value);}async setAccessLevel(){}}
function fakeChrome(options:{local?:Area;session?:Area}={}){const local=options.local??new Area(),session=options.session??new Area();const tabs:any[]=[];const createdWindows:any[]=[];const openWindows:any[]=[{id:10,type:'normal'}];const api:any={storage:{local,session},tabs:{query:async(query:any)=>query?.active?tabs.filter(tab=>tab.active):tabs,onCreated:new Event(),onUpdated:new Event(),onRemoved:new Event()},windows:{create:async(options:any)=>{const created={id:100+createdWindows.length,type:options.type??'normal',...options};createdWindows.push(created);return created;},getAll:async(options:any)=>openWindows.filter(window=>!options?.windowTypes||options.windowTypes.includes(window.type)),onRemoved:new Event()},runtime:{getURL:(path:string)=>`chrome-extension://selfrelay/${path}`,onInstalled:new Event(),onStartup:new Event(),onMessage:new Event()}};return{api,tabs,createdWindows,openWindows,local,session};}
function ids(prefix='id'){let value=0;return()=>`${prefix}-${++value}`;}
const now=()=> '2026-08-22T04:00:00.000Z';
function setActive(tabs:any[],id:number){for(const tab of tabs)tab.active=tab.id===id;}

test('normalizes supported URLs exactly like the preserved artifact',()=>{assert.equal(normalizeUrl('https://example.com/work/#part'),'https://example.com/work');assert.throws(()=>normalizeUrl('chrome://extensions'));assert.equal(contextKey('https://EXAMPLE.com/a','site'),'browser:site:https://example.com');});
test('matches tab/url/site scopes and prefers the most specific context',()=>{const base={id:'x',type:'browser',contextKey:'x',url:'https://example.com/work',origin:'https://example.com',title:'Work',faviconUrl:null,trackedTabId:null,createdAt:'1',updatedAt:'2'} satisfies Omit<BrowserContext,'scope'>;const site={...base,id:'site',scope:'site'} as BrowserContext;const url={...base,id:'url',scope:'url'} as BrowserContext;const tab={...base,id:'tab',scope:'tab',trackedTabId:7} as BrowserContext;assert.equal(matches(site,'https://example.com/other'),true);assert.equal(matches(url,'https://example.com/work#hash'),true);assert.equal(findBestContext([site,url,tab],'https://example.com/work',7)?.id,'tab');assert.equal(findBestContext([site,url],'https://example.com/work',9)?.id,'url');});
test('normal tab close continues to open one capture exactly as before',async()=>{const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});const tracked:any=await controller.trackContext('url');assert.equal(tracked.ok,true);await controller.handleRemoved(1,false,10);assert.equal(env.createdWindows.length,1);const pending=(await controller.storage.getPending())[0]!;assert.match(env.createdWindows[0].url,/checkpoint\.html\?pending=/);const saved:any=await controller.saveCheckpoint(pending.id,'  Ya probé A. Siguiente paso: B.  ');assert.equal(saved.ok,true);assert.equal(saved.nextPendingId,null);const recovered:any=await controller.lookupCheckpoint('https://example.com/work',2);assert.equal(recovered.checkpoint.originalText,'Ya probé A. Siguiente paso: B.');await controller.resolveCheckpoint(recovered.checkpoint.id);assert.equal((await controller.lookupCheckpoint('https://example.com/work',2) as any).checkpoint,null);});
test('several tabs from the same context in one closing window create one pending',async()=>{const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'https://example.com/work/a',title:'A',active:true},{id:2,windowId:10,url:'https://example.com/work/b',title:'B',active:false},{id:3,windowId:10,url:'https://example.com/work/c',title:'C',active:false});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('site');await controller.refreshAllTabs();await Promise.all([controller.handleRemoved(1,true,10),controller.handleRemoved(2,true,10),controller.handleRemoved(3,true,10)]);const pending=await controller.storage.getPending();assert.equal(pending.length,1);assert.equal(new Set(pending.map(item=>item.contextId)).size,1);assert.equal(env.createdWindows.length,0);assert.deepEqual(await controller.storage.getSnapshots(),{});});
test('different contexts in one closing window preserve one pending per context',async()=>{const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'https://one.example/work',title:'One',active:true},{id:2,windowId:10,url:'https://two.example/work',title:'Two',active:false});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');setActive(env.tabs,2);await controller.trackContext('url');await controller.refreshAllTabs();await Promise.all([controller.handleRemoved(1,true,10),controller.handleRemoved(2,true,10)]);const pending=await controller.storage.getPending();assert.equal(pending.length,2);assert.equal(new Set(pending.map(item=>item.contextId)).size,2);assert.equal(env.createdWindows.length,0);});
test('window-close deduplication does not erase an older legitimate pending for the same context',async()=>{const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});const tracked:any=await controller.trackContext('url');await controller.storage.setPending([{id:'older',contextId:tracked.context.id,url:'https://example.com/work',title:'Older interruption',closedAt:'2026-08-21T20:00:00.000Z'}]);await controller.handleRemoved(1,true,10);const pending=await controller.storage.getPending();assert.equal(pending.length,2);assert.equal(pending.filter(item=>item.contextId===tracked.context.id).length,2);});
test('full-window close persists captures and never opens a capture window during shutdown',async()=>{const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');await controller.handleRemoved(1,true,10);assert.equal(env.createdWindows.length,0);assert.equal((await controller.storage.getPending()).length,1);});
test('closing one whole window while another Chrome window remains surfaces one pending afterward',async()=>{const env=fakeChrome();env.openWindows.push({id:20,type:'normal'});env.tabs.push({id:1,windowId:10,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');await controller.handleRemoved(1,true,10);env.openWindows.splice(0,1);await controller.handleWindowRemoved(10);assert.equal(env.createdWindows.length,1);});
test('startup with one pending surfaces one capture',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'only',contextId:'c',url:'https://example.com',title:'Only',closedAt:'2026-08-22T04:00:00.000Z'}]);await controller.handleStartup();assert.equal(env.createdWindows.length,1);assert.match(env.createdWindows[0].url,/pending=only/);});
test('startup with several pending surfaces only one, choosing the oldest deterministically',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'new',contextId:'c2',url:'https://two.example',title:'New',closedAt:'2026-08-22T05:00:00.000Z'},{id:'old',contextId:'c1',url:'https://one.example',title:'Old',closedAt:'2026-08-22T04:00:00.000Z'}]);await controller.handleStartup();await controller.handleStartup();assert.equal(env.createdWindows.length,1);assert.match(env.createdWindows[0].url,/pending=old/);});
test('saving the first pending exposes the next pending in deterministic order',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'second',contextId:'c2',url:'https://two.example',title:'Second',closedAt:'2026-08-22T05:00:00.000Z'},{id:'first',contextId:'c1',url:'https://one.example',title:'First',closedAt:'2026-08-22T04:00:00.000Z'}]);const result:any=await controller.saveCheckpoint('first','Seguir por acá.');assert.equal(result.ok,true);assert.equal(result.nextPendingId,'second');assert.equal((await controller.storage.getPending()).length,1);assert.equal((await controller.getPendingCapture('second') as any).ok,true);});
test('discarding the first pending exposes the next pending in deterministic order',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'second',contextId:'c2',url:'https://two.example',title:'Second',closedAt:'2026-08-22T05:00:00.000Z'},{id:'first',contextId:'c1',url:'https://one.example',title:'First',closedAt:'2026-08-22T04:00:00.000Z'}]);const result:any=await controller.discardPending('first');assert.equal(result.ok,true);assert.equal(result.nextPendingId,'second');assert.equal((await controller.storage.getPending()).length,1);});
test('durable journal recovers a full Chrome shutdown even when onRemoved never completed',async()=>{const first=fakeChrome();first.tabs.push({id:1,windowId:10,url:'https://example.com/work',title:'Work',active:true});const before=createBackgroundController(first.api,{now,uuid:ids('before')});const tracked:any=await before.trackContext('url');assert.equal(Object.keys(await before.storage.getDurableSnapshots()).length,1);const restarted=fakeChrome({local:first.local,session:new Area()});const after=createBackgroundController(restarted.api,{now,uuid:ids('after')});await after.handleStartup();const pending=await after.storage.getPending();assert.equal(pending.length,1);assert.equal(pending[0]!.contextId,tracked.context.id);assert.equal(Object.keys(await after.storage.getDurableSnapshots()).length,0);assert.equal(restarted.createdWindows.length,1);});
test('startup dedupes same context across multiple windows from one full-browser shutdown',async()=>{const first=fakeChrome();first.tabs.push({id:1,windowId:10,url:'https://example.com/a',title:'A',active:true},{id:2,windowId:20,url:'https://example.com/b',title:'B',active:false});const before=createBackgroundController(first.api,{now,uuid:ids('before')});await before.trackContext('site');await before.refreshAllTabs();assert.equal(Object.keys(await before.storage.getDurableSnapshots()).length,2);const restarted=fakeChrome({local:first.local,session:new Area()});const after=createBackgroundController(restarted.api,{now,uuid:ids('after')});await after.handleStartup();assert.equal((await after.storage.getPending()).length,1);});
test('startup does not duplicate a pending already materialized before shutdown completed',async()=>{const first=fakeChrome();first.tabs.push({id:1,windowId:10,url:'https://example.com/work',title:'Work',active:true});const before=createBackgroundController(first.api,{now,uuid:ids('before')});await before.trackContext('url');const sessionId=await before.storage.getBrowserSessionId();const context=(await before.storage.getContexts())[0]!;await before.storage.setPending([{id:'already',contextId:context.id,url:'https://example.com/work',title:'Work',closedAt:now(),sourceKey:`session:${sessionId}:context:${context.id}:window:10`}]);const restarted=fakeChrome({local:first.local,session:new Area()});const after=createBackgroundController(restarted.api,{now,uuid:ids('after')});await after.handleStartup();assert.equal((await after.storage.getPending()).length,1);});
test('concurrent normal closes queue legitimate pending contexts but keep one visible capture',async()=>{const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'https://one.example/work',title:'One',active:true},{id:2,windowId:10,url:'https://two.example/work',title:'Two',active:false});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');setActive(env.tabs,2);await controller.trackContext('url');await controller.refreshAllTabs();await Promise.all([controller.handleRemoved(1,false,10),controller.handleRemoved(2,false,10)]);assert.equal((await controller.storage.getPending()).length,2);assert.equal(env.createdWindows.length,1);});
test('unsupported active pages are never tracked',async()=>{const env=fakeChrome();env.tabs.push({id:1,windowId:10,url:'chrome://extensions',title:'Extensions',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});assert.equal((await controller.getActiveState() as any).supported,false);await assert.rejects(()=>controller.trackContext('url'));});
