import assert from 'node:assert/strict';
import test from 'node:test';
import type {BrowserContext} from '@selfrelay/shared';
import {createBackgroundController,findBestContext} from '../src/background-core.ts';
import {contextKey,matches,normalizeUrl} from '../src/url.ts';

class Event<T extends (...args:any[])=>any>{listeners:T[]=[];addListener=(listener:T)=>{this.listeners.push(listener);};async emit(...args:Parameters<T>){for(const listener of this.listeners)await listener(...args);}}
class Area{data:Record<string,any>={};async get(key:string|string[]|Record<string,any>|null){if(typeof key==='string')return{[key]:this.data[key]};return{...this.data};}async set(value:Record<string,any>){Object.assign(this.data,value);}async setAccessLevel(){}}
function fakeChrome(){const local=new Area(),session=new Area();const tabs:any[]=[];const createdWindows:any[]=[];const api:any={storage:{local,session},tabs:{query:async(query:any)=>query?.active?tabs.filter(tab=>tab.active):tabs,onCreated:new Event(),onUpdated:new Event(),onRemoved:new Event()},windows:{create:async(options:any)=>{const created={id:100+createdWindows.length,...options};createdWindows.push(created);return created;},onRemoved:new Event()},runtime:{getURL:(path:string)=>`chrome-extension://selfrelay/${path}`,onInstalled:new Event(),onStartup:new Event(),onMessage:new Event()}};return{api,tabs,createdWindows,local,session};}
function ids(){let value=0;return()=>`id-${++value}`;}
const now=()=> '2026-08-22T04:00:00.000Z';
function setActive(tabs:any[],id:number){for(const tab of tabs)tab.active=tab.id===id;}

test('normalizes supported URLs exactly like the preserved artifact',()=>{assert.equal(normalizeUrl('https://example.com/work/#part'),'https://example.com/work');assert.throws(()=>normalizeUrl('chrome://extensions'));assert.equal(contextKey('https://EXAMPLE.com/a','site'),'browser:site:https://example.com');});

test('matches tab/url/site scopes and prefers the most specific context',()=>{const base={id:'x',type:'browser',contextKey:'x',url:'https://example.com/work',origin:'https://example.com',title:'Work',faviconUrl:null,trackedTabId:null,createdAt:'1',updatedAt:'2'} satisfies Omit<BrowserContext,'scope'>;const site={...base,id:'site',scope:'site'} as BrowserContext;const url={...base,id:'url',scope:'url'} as BrowserContext;const tab={...base,id:'tab',scope:'tab',trackedTabId:7} as BrowserContext;assert.equal(matches(site,'https://example.com/other'),true);assert.equal(matches(url,'https://example.com/work#hash'),true);assert.equal(findBestContext([site,url,tab],'https://example.com/work',7)?.id,'tab');assert.equal(findBestContext([site,url],'https://example.com/work',9)?.id,'url');});

test('normal tab close continues to open one capture exactly as before',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});const tracked:any=await controller.trackContext('url');assert.equal(tracked.ok,true);await controller.handleRemoved(1,false);assert.equal(env.createdWindows.length,1);const pending=(await controller.storage.getPending())[0]!;assert.match(env.createdWindows[0].url,/checkpoint\.html\?pending=/);const saved:any=await controller.saveCheckpoint(pending.id,'  Ya probé A. Siguiente paso: B.  ');assert.equal(saved.ok,true);assert.equal(saved.nextPendingId,null);const recovered:any=await controller.lookupCheckpoint('https://example.com/work',2);assert.equal(recovered.checkpoint.originalText,'Ya probé A. Siguiente paso: B.');await controller.resolveCheckpoint(recovered.checkpoint.id);const after:any=await controller.lookupCheckpoint('https://example.com/work',2);assert.equal(after.checkpoint,null);});

test('several tabs from the same context closing together create one pending capture',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/work/a',title:'A',active:true},{id:2,url:'https://example.com/work/b',title:'B',active:false});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('site');await controller.refreshAllTabs();await Promise.all([controller.handleRemoved(1,true),controller.handleRemoved(2,true)]);const pending=await controller.storage.getPending();assert.equal(pending.length,1);assert.equal(env.createdWindows.length,0);});

test('several different contexts closing together preserve one pending per context',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/one',title:'One',active:true},{id:2,url:'https://example.com/two',title:'Two',active:false});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');setActive(env.tabs,2);await controller.trackContext('url');await controller.refreshAllTabs();await Promise.all([controller.handleRemoved(1,true),controller.handleRemoved(2,true)]);const pending=await controller.storage.getPending();assert.equal(pending.length,2);assert.equal(new Set(pending.map(item=>item.contextId)).size,2);assert.equal(env.createdWindows.length,0);});

test('an already pending context is not duplicated by another close',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/work',title:'Work',active:true},{id:2,url:'https://example.com/work',title:'Work duplicate',active:false});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');await controller.refreshAllTabs();await controller.handleRemoved(1,true);await controller.handleRemoved(2,true);assert.equal((await controller.storage.getPending()).length,1);});

test('full-window close persists capture without forcing a popup',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');await controller.handleRemoved(1,true);assert.equal(env.createdWindows.length,0);assert.equal((await controller.storage.getPending()).length,1);});

test('startup with one pending surfaces one capture',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'only',contextId:'c',url:'https://example.com',title:'Only',closedAt:'2026-08-22T04:00:00.000Z'}]);await controller.handleStartup();assert.equal(env.createdWindows.length,1);assert.match(env.createdWindows[0].url,/pending=only/);});

test('startup with several pending surfaces only the oldest capture',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'new',contextId:'c2',url:'https://two.example',title:'New',closedAt:'2026-08-22T05:00:00.000Z'},{id:'old',contextId:'c1',url:'https://one.example',title:'Old',closedAt:'2026-08-22T04:00:00.000Z'}]);await controller.handleStartup();assert.equal(env.createdWindows.length,1);assert.match(env.createdWindows[0].url,/pending=old/);});

test('saving the first pending returns the next pending in deterministic order',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'second',contextId:'c2',url:'https://two.example',title:'Second',closedAt:'2026-08-22T05:00:00.000Z'},{id:'first',contextId:'c1',url:'https://one.example',title:'First',closedAt:'2026-08-22T04:00:00.000Z'}]);const result:any=await controller.saveCheckpoint('first','Seguir por acá.');assert.equal(result.ok,true);assert.equal(result.nextPendingId,'second');assert.equal((await controller.storage.getPending()).length,1);assert.equal((await controller.getPendingCapture('second') as any).ok,true);});

test('discarding the first pending returns the next pending in deterministic order',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'second',contextId:'c2',url:'https://two.example',title:'Second',closedAt:'2026-08-22T05:00:00.000Z'},{id:'first',contextId:'c1',url:'https://one.example',title:'First',closedAt:'2026-08-22T04:00:00.000Z'}]);const result:any=await controller.discardPending('first');assert.equal(result.ok,true);assert.equal(result.nextPendingId,'second');assert.equal((await controller.storage.getPending()).length,1);});

test('concurrent normal closes keep a single visible capture while queueing legitimate pending contexts',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/one',title:'One',active:true},{id:2,url:'https://example.com/two',title:'Two',active:false});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');setActive(env.tabs,2);await controller.trackContext('url');await controller.refreshAllTabs();await Promise.all([controller.handleRemoved(1,false),controller.handleRemoved(2,false)]);assert.equal((await controller.storage.getPending()).length,2);assert.equal(env.createdWindows.length,1);});

test('unsupported active pages are never tracked',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'chrome://extensions',title:'Extensions',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});const state:any=await controller.getActiveState();assert.equal(state.supported,false);await assert.rejects(()=>controller.trackContext('url'));});
