import assert from 'node:assert/strict';
import test from 'node:test';
import type {BrowserContext} from '@selfrelay/shared';
import {createBackgroundController,findBestContext} from '../src/background-core.ts';
import {contextKey,matches,normalizeUrl} from '../src/url.ts';

class Event<T extends (...args:any[])=>any>{listeners:T[]=[];addListener=(listener:T)=>{this.listeners.push(listener);};async emit(...args:Parameters<T>){for(const listener of this.listeners)await listener(...args);}}
class Area{data:Record<string,any>={};async get(key:string|string[]|Record<string,any>|null){if(typeof key==='string')return{[key]:this.data[key]};return{...this.data};}async set(value:Record<string,any>){Object.assign(this.data,value);}async setAccessLevel(){}}
function fakeChrome(){const local=new Area(),session=new Area();const tabs:any[]=[];const createdWindows:any[]=[];const api:any={storage:{local,session},tabs:{query:async(query:any)=>query?.active?tabs.filter(tab=>tab.active):tabs,onCreated:new Event(),onUpdated:new Event(),onRemoved:new Event()},windows:{create:async(options:any)=>{createdWindows.push(options);return{id:createdWindows.length,...options};}},runtime:{getURL:(path:string)=>`chrome-extension://selfrelay/${path}`,onInstalled:new Event(),onStartup:new Event(),onMessage:new Event()}};return{api,tabs,createdWindows,local,session};}
function ids(){let value=0;return()=>`id-${++value}`;}
const now=()=> '2026-08-22T04:00:00.000Z';

test('normalizes supported URLs exactly like the preserved artifact',()=>{assert.equal(normalizeUrl('https://example.com/work/#part'),'https://example.com/work');assert.throws(()=>normalizeUrl('chrome://extensions'));assert.equal(contextKey('https://EXAMPLE.com/a','site'),'browser:site:https://example.com');});

test('matches tab/url/site scopes and prefers the most specific context',()=>{const base={id:'x',type:'browser',contextKey:'x',url:'https://example.com/work',origin:'https://example.com',title:'Work',faviconUrl:null,trackedTabId:null,createdAt:'1',updatedAt:'2'} satisfies Omit<BrowserContext,'scope'>;const site={...base,id:'site',scope:'site'} as BrowserContext;const url={...base,id:'url',scope:'url'} as BrowserContext;const tab={...base,id:'tab',scope:'tab',trackedTabId:7} as BrowserContext;assert.equal(matches(site,'https://example.com/other'),true);assert.equal(matches(url,'https://example.com/work#hash'),true);assert.equal(findBestContext([site,url,tab],'https://example.com/work',7)?.id,'tab');assert.equal(findBestContext([site,url],'https://example.com/work',9)?.id,'url');});

test('follow → close → capture → save → return → automatic recovery → resolve',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});const tracked:any=await controller.trackContext('url');assert.equal(tracked.ok,true);await controller.handleRemoved(1,false);assert.equal(env.createdWindows.length,1);const pending=(await controller.storage.getPending())[0]!;assert.match(env.createdWindows[0].url,/checkpoint\.html\?pending=/);const saved:any=await controller.saveCheckpoint(pending.id,'  Ya probé A. Siguiente paso: B.  ');assert.equal(saved.ok,true);const recovered:any=await controller.lookupCheckpoint('https://example.com/work',2);assert.equal(recovered.checkpoint.originalText,'Ya probé A. Siguiente paso: B.');await controller.resolveCheckpoint(recovered.checkpoint.id);const after:any=await controller.lookupCheckpoint('https://example.com/work',2);assert.equal(after.checkpoint,null);});

test('full-window close persists capture without forcing a popup',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'https://example.com/work',title:'Work',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.trackContext('url');await controller.handleRemoved(1,true);assert.equal(env.createdWindows.length,0);assert.equal((await controller.storage.getPending()).length,1);});

test('startup surfaces the oldest persisted pending capture',async()=>{const env=fakeChrome();const controller=createBackgroundController(env.api,{now,uuid:ids()});await controller.storage.setPending([{id:'new',contextId:'c',url:'https://example.com',title:'New',closedAt:'2026-08-22T05:00:00.000Z'},{id:'old',contextId:'c',url:'https://example.com',title:'Old',closedAt:'2026-08-22T04:00:00.000Z'}]);await controller.handleStartup();assert.equal(env.createdWindows.length,1);assert.match(env.createdWindows[0].url,/pending=old/);});

test('unsupported active pages are never tracked',async()=>{const env=fakeChrome();env.tabs.push({id:1,url:'chrome://extensions',title:'Extensions',active:true});const controller=createBackgroundController(env.api,{now,uuid:ids()});const state:any=await controller.getActiveState();assert.equal(state.supported,false);await assert.rejects(()=>controller.trackContext('url'));});
