import assert from 'node:assert/strict';
import test from 'node:test';
import {createBackgroundController} from '../src/background-core.ts';

class Event<T extends (...args:any[])=>any>{listeners:T[]=[];addListener=(listener:T)=>{this.listeners.push(listener);};}
class Area{data:Record<string,any>={};async get(key:string|string[]|Record<string,any>|null){if(typeof key==='string')return{[key]:this.data[key]};if(Array.isArray(key))return Object.fromEntries(key.map(item=>[item,this.data[item]]));if(key&&typeof key==='object')return Object.fromEntries(Object.entries(key).map(([item,fallback])=>[item,this.data[item]??fallback]));return{...this.data};}async set(value:Record<string,any>){Object.assign(this.data,value);}async setAccessLevel(){}}
function fakeChrome(options:{local?:Area;session?:Area}={}){
  const local=options.local??new Area(),session=options.session??new Area();const tabs:any[]=[];const createdTabs:any[]=[];const createdWindows:any[]=[];let nextTab=100;
  const api:any={storage:{local,session},tabs:{query:async(query:any)=>query?.active?tabs.filter(tab=>tab.active):tabs,create:async(options:any)=>{const tab={id:nextTab++,windowId:options.windowId??10,url:options.url,title:options.url,active:Boolean(options.active)};tabs.push(tab);createdTabs.push(tab);return tab;},onCreated:new Event(),onUpdated:new Event(),onRemoved:new Event()},windows:{create:async(options:any)=>{const created={id:200+createdWindows.length,...options};createdWindows.push(created);return created;},getAll:async()=>[{id:10,type:'normal'}],onRemoved:new Event()},runtime:{getURL:(path:string)=>`chrome-extension://selfrelay/${path}`,sendMessage:async()=>({ok:false}),onInstalled:new Event(),onStartup:new Event(),onMessage:new Event()},offscreen:{hasDocument:async()=>true,createDocument:async()=>{}}};
  return{api,tabs,createdTabs,createdWindows,local,session};
}
function ids(prefix='id'){let value=0;return()=>`${prefix}-${++value}`;}
const now=()=> '2026-08-22T16:00:00.000Z';
function addTabs(env:ReturnType<typeof fakeChrome>,count=4,windows:number[]=[]){for(let i=0;i<count;i++)env.tabs.push({id:i+1,windowId:windows[i]??10,url:`https://${String.fromCharCode(97+i)}.example/work`,title:`Tab ${i+1}`,faviconUrl:null,active:i===0});}
async function makeWorkset(count=4,windows:number[]=[]){const env=fakeChrome();addTabs(env,count,windows);const controller=createBackgroundController(env.api,{now,uuid:ids()});const result:any=await controller.upsertWorkset(env.tabs.map(tab=>tab.id));assert.equal(result.ok,true);return{env,controller,context:result.context};}
function pending(context:any,id='pending'){return{id,contextId:context.id,url:context.members[0].url,title:'Work',closedAt:now(),memberId:context.members[0].id};}

test('workset supports a single explicitly selected tab',async()=>{const {controller,context}=await makeWorkset(1);assert.equal(context.members.length,1);assert.equal((await controller.storage.getSnapshots() as any)['1'].memberId,context.members[0].id);});

test('workset supports four tabs and preserves selection order',async()=>{const {context}=await makeWorkset(4);assert.deepEqual(context.members.map((member:any)=>member.url),['https://a.example/work','https://b.example/work','https://c.example/work','https://d.example/work']);assert.deepEqual(context.members.map((member:any)=>member.order),[0,1,2,3]);});

test('tabs can be added to and removed from an existing workset',async()=>{const {env,controller,context}=await makeWorkset(2);env.tabs.push({id:3,windowId:10,url:'https://c.example/work',title:'Tab 3',active:false});const updated:any=await controller.upsertWorkset([1,2,3],context.id);assert.equal(updated.context.members.length,3);const removed:any=await controller.removeWorksetMember(context.id,updated.context.members[1].id);assert.equal(removed.ok,true);assert.deepEqual(removed.context.members.map((member:any)=>member.url),['https://a.example/work','https://c.example/work']);});

test('closing one workset tab does not create a pending while another remains',async()=>{const {controller}=await makeWorkset(4);await controller.handleRemoved(1,false,10);assert.equal((await controller.storage.getPending()).length,0);assert.equal(Object.keys(await controller.storage.getSnapshots()).length,3);});

test('closing the final workset tab creates one pending and one capture surface',async()=>{const {controller,env}=await makeWorkset(4);for(const id of [1,2,3])await controller.handleRemoved(id,false,10);assert.equal((await controller.storage.getPending()).length,0);await controller.handleRemoved(4,false,10);assert.equal((await controller.storage.getPending()).length,1);assert.equal(env.createdWindows.length,1);});

test('closing a window containing an entire workset creates exactly one pending',async()=>{const {controller}=await makeWorkset(4);await controller.handleRemoved(1,true,10);assert.equal((await controller.storage.getPending()).length,1);assert.equal(Object.keys(await controller.storage.getSnapshots()).length,0);});

test('closing one workset window does not end the context while another workset window remains',async()=>{const {controller}=await makeWorkset(4,[10,10,20,20]);await controller.handleRemoved(1,true,10);assert.equal((await controller.storage.getPending()).length,0);assert.equal(Object.keys(await controller.storage.getSnapshots()).length,2);await controller.handleRemoved(3,true,20);assert.equal((await controller.storage.getPending()).length,1);});

test('durable shutdown journal recovers one pending for a multi-tab workset',async()=>{const first=fakeChrome();addTabs(first,4);const before=createBackgroundController(first.api,{now,uuid:ids('before')});const made:any=await before.upsertWorkset([1,2,3,4]);assert.equal(Object.keys(await before.storage.getDurableSnapshots()).length,4);const restarted=fakeChrome({local:first.local,session:new Area()});const after=createBackgroundController(restarted.api,{now,uuid:ids('after')});await after.handleStartup();const items=await after.storage.getPending();assert.equal(items.length,1);assert.equal(items[0]!.contextId,made.context.id);});

test('one general checkpoint is recovered from any member without duplication',async()=>{const {controller,context}=await makeWorkset(4);await controller.storage.setPending([pending(context)]);const saved:any=await controller.saveCheckpoint('pending',{text:'Continuar implementación.'});assert.equal(saved.ok,true);for(const member of context.members){const found:any=await controller.lookupCheckpoint(member.url);assert.equal(found.checkpoint.id,saved.checkpoint.id);}assert.equal((await controller.storage.getCheckpoints()).length,1);});

test('subset checkpoint appears only on selected members',async()=>{const {controller,context}=await makeWorkset(4);const [a,b,,d]=context.members;await controller.storage.setPending([pending(context)]);const general:any=await controller.saveCheckpoint('pending',{text:'General'});await controller.storage.setPending([pending(context,'subset')]);const subset:any=await controller.saveCheckpoint('subset',{text:'Subset',targetMemberIds:[a.id,b.id,d.id]});assert.deepEqual(subset.checkpoint.targetMemberIds,[a.id,b.id,d.id]);assert.equal((await controller.lookupCheckpoint(a.url) as any).checkpoint.id,subset.checkpoint.id);assert.equal((await controller.lookupCheckpoint(context.members[2].url) as any).checkpoint.id,general.checkpoint.id);});

test('per-tab checkpoint outranks subset and general checkpoint on that member',async()=>{const {controller,context}=await makeWorkset(4);const [a,b,,d]=context.members;await controller.storage.setPending([pending(context,'general')]);const general:any=await controller.saveCheckpoint('general',{text:'General'});await controller.storage.setPending([pending(context,'subset')]);const subset:any=await controller.saveCheckpoint('subset',{text:'Subset',targetMemberIds:[a.id,b.id,d.id]});await controller.storage.setPending([pending(context,'specific')]);const specific:any=await controller.saveCheckpoint('specific',{text:'Specific',targetMemberIds:[a.id]});assert.equal((await controller.lookupCheckpoint(a.url) as any).checkpoint.id,specific.checkpoint.id);assert.equal((await controller.lookupCheckpoint(b.url) as any).checkpoint.id,subset.checkpoint.id);assert.equal((await controller.lookupCheckpoint(context.members[2].url) as any).checkpoint.id,general.checkpoint.id);});

test('restoration opens only missing workset tabs and never duplicates already-open tabs',async()=>{const {controller,env,context}=await makeWorkset(4);env.tabs.splice(1);const state:any=await controller.getContextTabState(context.id);assert.equal(state.missing.length,3);const opened:any=await controller.openMissingContextTabs(context.id,10);assert.equal(opened.opened,3);assert.equal(env.createdTabs.length,3);const second:any=await controller.openMissingContextTabs(context.id,10);assert.equal(second.opened,0);assert.equal(env.createdTabs.length,3);});

test('restoration ignores unsupported URLs even if old storage contains one',async()=>{const {controller,env,context}=await makeWorkset(1);const contexts=await controller.storage.getContexts();contexts[0]={...contexts[0]!,members:[...contexts[0]!.members!,{id:'unsafe',url:'chrome://extensions',title:'Unsafe',faviconUrl:null,order:1,addedAt:now()}]};await controller.storage.setContexts(contexts);env.tabs.splice(0);const opened:any=await controller.openMissingContextTabs(context.id,10);assert.equal(opened.opened,1);assert.equal(env.createdTabs.some(tab=>String(tab.url).startsWith('chrome://')),false);});

test('saving and looking up audio never invokes transcription; explicit request does and persists it once',async()=>{let calls=0;const env=fakeChrome();addTabs(env,1);const controller=createBackgroundController(env.api,{now,uuid:ids(),transcribeAudio:async()=>{calls++;return{text:'Mañana revisar autenticación.',engine:'whisper-local'};}});const made:any=await controller.upsertWorkset([1]);await controller.storage.setPending([pending(made.context)]);const saved:any=await controller.saveCheckpoint('pending',{audioRef:'audio-1',audioMimeType:'audio/webm'});assert.equal(calls,0);assert.equal(saved.checkpoint.transcript,null);await controller.lookupCheckpoint(made.context.members[0].url);assert.equal(calls,0);const transcribed:any=await controller.transcribeCheckpoint(saved.checkpoint.id,'es-UY');assert.equal(transcribed.ok,true);assert.equal(calls,1);assert.equal(transcribed.checkpoint.transcript,'Mañana revisar autenticación.');const cached:any=await controller.transcribeCheckpoint(saved.checkpoint.id,'es-UY');assert.equal(cached.cached,true);assert.equal(calls,1);});

test('failed on-demand transcription preserves audio and can be retried',async()=>{let calls=0;const env=fakeChrome();addTabs(env,1);const controller=createBackgroundController(env.api,{now,uuid:ids(),transcribeAudio:async()=>{calls++;return calls===1?null:{text:'Segundo intento correcto.',engine:'whisper-local'};}});const made:any=await controller.upsertWorkset([1]);await controller.storage.setPending([pending(made.context)]);const saved:any=await controller.saveCheckpoint('pending',{audioRef:'audio-retry'});const first:any=await controller.transcribeCheckpoint(saved.checkpoint.id,'es');assert.equal(first.ok,false);const stored=(await controller.storage.getCheckpoints())[0]!;assert.equal(stored.audioRef,'audio-retry');assert.equal(stored.transcript,null);const retry:any=await controller.transcribeCheckpoint(saved.checkpoint.id,'es');assert.equal(retry.ok,true);assert.equal(retry.checkpoint.transcript,'Segundo intento correcto.');assert.equal(calls,2);});
